-- Migration: 002_seed_content
-- Description: Seed default terms_sections and policy_sections
-- Run after: 001_initial_schema.sql
-- Run: psql -U root -d Nine_housing -f scripts/migrations/002_seed_content.sql

INSERT INTO terms_sections (section_id, title, content, sort_order) VALUES
('acceptance', 'Chấp nhận điều khoản', 'Bằng việc truy cập và sử dụng website NineHousing (bao gồm ứng dụng di động nếu có), bạn đồng ý tuân thủ các Điều khoản sử dụng này. Nếu bạn không đồng ý, vui lòng không sử dụng dịch vụ. Chúng tôi có quyền cập nhật điều khoản bất kỳ lúc nào; phiên bản hiện tại luôn được đăng trên trang này.', 1),
('service', 'Mô tả dịch vụ', 'NineHousing là nền tảng trung gian kết nối người dùng với các khách sạn, resort và chỗ lưu trú. Chúng tôi không sở hữu hoặc vận hành các cơ sở lưu trú mà chỉ cung cấp công cụ tìm kiếm, so sánh giá và đặt phòng. Hợp đồng đặt phòng thực chất được tạo giữa bạn và đơn vị cung cấp chỗ ở; NineHousing chịu trách nhiệm trong phạm vi nền tảng và chính sách của mình.', 2),
('booking', 'Đặt phòng và thanh toán', 'Khi đặt phòng, bạn cam kết cung cấp thông tin chính xác và đủ. Giá hiển thị đã bao gồm thuế và phí theo quy định trừ khi có ghi chú khác. Thanh toán được thực hiện qua cổng an toàn; bạn chịu trách nhiệm đảm bảo tài khoản/thẻ có đủ số dư. Chính sách hủy phòng, hoàn tiền áp dụng theo từng khách sạn và được hiển thị trước khi xác nhận đặt phòng.', 3),
('account', 'Tài khoản người dùng', 'Bạn có thể đăng ký tài khoản để lưu thông tin, xem lịch sử đặt phòng và nhận ưu đãi. Bạn chịu trách nhiệm bảo mật mật khẩu và mọi hoạt động diễn ra qua tài khoản của mình. NineHousing không yêu cầu mật khẩu qua email hoặc điện thoại; hãy cảnh giác với lừa đảo. Chúng tôi có quyền vô hiệu hóa tài khoản nếu vi phạm điều khoản hoặc pháp luật.', 4),
('conduct', 'Hành vi sử dụng', 'Bạn không được: sử dụng dịch vụ cho mục đích bất hợp pháp hoặc vi phạm quyền của bên thứ ba; đăng nội dung sai lệch, xúc phạm hoặc spam; can thiệp hệ thống, crawl dữ liệu trái phép hoặc tạo tài khoản giả; đặt phòng giả để chiếm ưu đãi hoặc gây thiệt hại cho khách sạn. Vi phạm có thể dẫn đến chặn truy cập và/hoặc truy cứu pháp lý.', 5),
('liability', 'Giới hạn trách nhiệm', 'NineHousing nỗ lực đảm bảo thông tin trên nền tảng chính xác nhưng không bảo đảm hoàn toàn do dữ liệu do đối tác cung cấp. Trong phạm vi pháp luật cho phép, chúng tôi không chịu trách nhiệm gián tiếp, thiệt hại do gián đoạn dịch vụ, lỗi kỹ thuật hoặc hành vi của khách sạn/bên thứ ba. Trách nhiệm tối đa của NineHousing trong mỗi giao dịch có thể bị giới hạn theo quy định áp dụng.', 6),
('contact', 'Liên hệ', 'Mọi thắc mắc về Điều khoản sử dụng hoặc dịch vụ, vui lòng liên hệ: Email: support@ninehousing.com | Hotline: 1900 xxxx (giờ hành chính). Chúng tôi sẽ phản hồi trong thời gian sớm nhất.', 7)
ON CONFLICT (section_id) DO NOTHING;

INSERT INTO policy_sections (section_id, title, content, sort_order) VALUES
('intro', 'Giới thiệu', 'Chính sách này mô tả cách NineHousing thu thập, sử dụng và bảo vệ thông tin cá nhân của bạn khi sử dụng nền tảng đặt phòng khách sạn. Chúng tôi cam kết bảo mật thông tin và minh bạch trong mọi hoạt động xử lý dữ liệu.', 1),
('collect', 'Thông tin chúng tôi thu thập', 'Chúng tôi có thể thu thập: (1) Thông tin bạn cung cấp: họ tên, email, số điện thoại, địa chỉ khi đặt phòng hoặc đăng ký tài khoản. (2) Thông tin thanh toán: thẻ tín dụng/ghi nợ được xử lý qua cổng thanh toán bảo mật, NineHousing không lưu trữ số thẻ đầy đủ. (3) Thông tin tự động: địa chỉ IP, loại thiết bị, trình duyệt khi bạn truy cập website để cải thiện trải nghiệm và bảo mật.', 2),
('use', 'Mục đích sử dụng', 'Thông tin được sử dụng để: xử lý đặt phòng và gửi xác nhận; liên hệ hỗ trợ khách hàng; gửi thông tin khuyến mãi (nếu bạn đồng ý); cải thiện website và dịch vụ; tuân thủ quy định pháp luật. Chúng tôi không bán hoặc cho thuê dữ liệu cá nhân của bạn cho bên thứ ba vì mục đích marketing.', 3),
('share', 'Chia sẻ thông tin', 'Chúng tôi có thể chia sẻ thông tin với: (1) Khách sạn/đối tác lưu trú để hoàn tất đặt phòng. (2) Đơn vị xử lý thanh toán để thực hiện giao dịch. (3) Cơ quan có thẩm quyền khi pháp luật yêu cầu. Các đối tác đều cam kết bảo mật theo chuẩn và chỉ sử dụng đúng mục đích.', 4),
('security', 'Bảo mật', 'NineHousing áp dụng các biện pháp kỹ thuật và tổ chức phù hợp để bảo vệ dữ liệu: mã hóa kết nối (SSL/TLS), hạn chế quyền truy cập nội bộ, và cập nhật thường xuyên. Trong trường hợp sự cố rò rỉ dữ liệu có thể ảnh hưởng đến bạn, chúng tôi sẽ thông báo trong thời gian sớm nhất theo quy định.', 5),
('rights', 'Quyền của bạn', 'Bạn có quyền: truy cập và xem dữ liệu cá nhân mà chúng tôi lưu trữ; yêu cầu chỉnh sửa hoặc xóa dữ liệu (trừ trường hợp pháp luật yêu cầu lưu giữ); rút lại đồng ý với marketing bất kỳ lúc nào; khiếu nại với cơ quan bảo vệ dữ liệu. Để thực hiện các quyền trên, vui lòng liên hệ qua email hoặc mục Liên hệ trên website.', 6),
('update', 'Cập nhật chính sách', 'Chính sách này có thể được cập nhật theo thay đổi pháp luật hoặc hoạt động kinh doanh. Phiên bản mới sẽ được đăng trên trang này với ngày cập nhật. Việc bạn tiếp tục sử dụng dịch vụ sau khi đăng chính sách mới được coi là chấp nhận. Nếu có thay đổi quan trọng, chúng tôi có thể gửi thông báo qua email.', 7)
ON CONFLICT (section_id) DO NOTHING;
