-- Seed properties (hotels) for NineHousing
-- Run: node scripts/run-seeds.js
-- Idempotent: ON CONFLICT (slug) DO UPDATE

INSERT INTO properties (
  slug, name, location, province, district, ward, address, description,
  image, images, raw_price, price_type, stars, rating, reviews, views, badge,
  amenities, specs, detailed_amenities, max_guests
) VALUES
(
  'vinpearl-luxury-nha-trang',
  'Vinpearl Luxury Nha Trang',
  'Nha Trang, Khánh Hòa',
  'Khánh Hòa', 'Nha Trang', '', '',
  'Tọa lạc tại vị trí đắc địa trên đảo Hòn Tre, Vinpearl Luxury mang đến không gian nghỉ dưỡng biệt lập đẳng cấp.',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
  ARRAY[
    'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80',
    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80'
  ],
  170, 'month', 5, 9.4, '1.280', '24.5K', 'HOT DEAL',
  ARRAY['Restaurant', 'Cable TV', 'Wi Fi', 'Balcony'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "47"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi vô cực riêng"}, {"icon": "fa-solid fa-spa", "text": "Akoya Spa trên mặt nước"}, {"icon": "fa-solid fa-utensils", "text": "Bữa sáng Buffet quốc tế"}]'::jsonb,
  4
),
(
  'intercontinental-da-nang',
  'InterContinental Đà Nẵng',
  'Sơn Trà, Đà Nẵng',
  'Đà Nẵng', 'Sơn Trà', '', '',
  'Khu nghỉ dưỡng huyền thoại InterContinental Danang Sun Peninsula Chung cư được thiết kế bởi Bill Bensley.',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
  ARRAY[
    'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80',
    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80'
  ],
  272, 'month', 5, 9.7, '987', '18.2K', 'SANG TRỌNG',
  ARRAY['Air conditioner', 'Balcony', 'Washing machine', 'Bus'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "78"}'::jsonb,
  '[{"icon": "fa-solid fa-umbrella-beach", "text": "Bãi biển riêng tư"}, {"icon": "fa-solid fa-wine-glass", "text": "Nhà hàng La Maison 1888"}, {"icon": "fa-solid fa-hot-tub-person", "text": "HARNN Heritage Spa"}]'::jsonb,
  4
),
(
  'sofitel-legend-metropole',
  'Sofitel Legend Metropole',
  'Hoàn Kiếm, Hà Nội',
  'Hà Nội', 'Hoàn Kiếm', '', '',
  'Biểu tượng của sự thanh lịch Pháp giữa lòng thủ đô ngàn năm văn hiến. Kể từ năm 1901...',
  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
  ARRAY[
    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80',
    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80'
  ],
  220, 'month', 5, 9.5, '2.041', '32.1K', 'LỊCH SỬ',
  ARRAY['Smoking', 'Heater', 'Wi Fi', 'Lift'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "72"}'::jsonb,
  '[{"icon": "fa-solid fa-building-columns", "text": "Kiến trúc Pháp cổ điển"}, {"icon": "fa-solid fa-mug-saucer", "text": "Bữa sáng kiểu Âu"}, {"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi nước ấm trong nhà"}]'::jsonb,
  2
),
(
  'muong-thanh-luxury-da-nang',
  'Mường Thanh Luxury Đà Nẵng',
  'Ngũ Hành Sơn, Đà Nẵng',
  'Đà Nẵng', 'Ngũ Hành Sơn', '', '',
  'Nằm ngay sát bãi biển Mỹ Khê tuyệt đẹp, căn hộ 4 sao mang đến trải nghiệm nghỉ dưỡng thoải mái với mức giá hợp lý.',
  'https://images.unsplash.com/photo-1542314831-c6a4d27ce66f?w=600&q=80',
  ARRAY[
    'https://images.unsplash.com/photo-1542314831-c6a4d27ce66f?w=1200&q=80',
    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80'
  ],
  60, 'month', 4, 8.8, '3.120', '15.5K', 'GIÁ TỐT',
  ARRAY['Shop', 'Cable TV', 'Heater', 'Washing machine'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "72"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi ngoài trời"}, {"icon": "fa-solid fa-utensils", "text": "Buffet sáng đa dạng"}, {"icon": "fa-solid fa-dumbbell", "text": "Phòng Gym"}]'::jsonb,
  2
),
(
  'the-myst-dong-khoi',
  'The Myst Dong Khoi',
  'Quận 1, TP.HCM',
  'TP.HCM', 'Quận 1', '', '',
  'Mang đậm dấu ấn Sài Gòn xưa pha trộn với thiết kế đương đại, The Myst mang đến một ốc đảo bình yên.',
  'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80',
  ARRAY[
    'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&q=80',
    'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200&q=80'
  ],
  128, 'month', 5, 9.3, '1.540', '20.1K', 'BOUTIQUE',
  ARRAY['Cable TV', 'Balcony', 'Wi Fi', 'Shop'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "67"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi tầng thượng"}, {"icon": "fa-solid fa-mug-hot", "text": "Trà chiều miễn phí"}, {"icon": "fa-solid fa-bath", "text": "Bồn tắm ngoài ban công"}]'::jsonb,
  2
),
(
  'ladas-eco-house-hoi-an',
  'Lada''s Eco House Hội An',
  'Cẩm Châu, Hội An',
  'Quảng Nam', 'Hội An', 'Cẩm Châu', '',
  'Homestay mộc mạc ẩn mình giữa cánh đồng lúa xanh mướt của Hội An. Trải nghiệm cuộc sống yên bình.',
  'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=1200&q=80'],
  34, 'month', 3, 9.0, '420', '5.2K', '',
  ARRAY['Cable TV', 'Smoking', 'Bus', 'Balcony'],
  '{"bedrooms": "3", "bathrooms": "2", "area": "104"}'::jsonb,
  '[{"icon": "fa-solid fa-bicycle", "text": "Mượn xe đạp miễn phí"}, {"icon": "fa-solid fa-leaf", "text": "Sân vườn rộng rãi"}, {"icon": "fa-solid fa-kitchen-set", "text": "Bếp nấu ăn chung"}]'::jsonb,
  2
),
(
  'six-senses-ninh-van-bay',
  'Six Senses Ninh Vân Bay',
  'Ninh Vân, Khánh Hòa',
  'Khánh Hòa', 'Ninh Hòa', '', '',
  'Chung cư ẩn mình trong vịnh Ninh Vân, mỗi villa có bể bơi riêng và view biển tuyệt đẹp.',
  'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=80'],
  480, 'month', 5, 9.8, '520', '12.1K', 'SANG TRỌNG',
  ARRAY['Air conditioner', 'Balcony', 'Smoking', 'Cable TV'],
  '{"bedrooms": "3", "bathrooms": "2", "area": "104"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Bể bơi riêng mỗi villa"}, {"icon": "fa-solid fa-spa", "text": "Six Senses Spa"}]'::jsonb,
  3
),
(
  'amanoi-ninh-thuan',
  'Amanoi Ninh Thuận',
  'Vĩnh Hy, Ninh Thuận',
  'Ninh Thuận', 'Ninh Hải', '', '',
  'Khu nghỉ dưỡng trong Vườn quốc gia Núi Chúa, kiến trúc tối giản đẳng cấp.',
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80'],
  600, 'month', 5, 9.6, '380', '9.8K', 'LUXURY',
  ARRAY['Cable TV', 'Air conditioner', 'Restaurant', 'Shop'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "64"}'::jsonb,
  '[{"icon": "fa-solid fa-spa", "text": "Aman Spa"}, {"icon": "fa-solid fa-om", "text": "Yoga Pavilion"}]'::jsonb,
  2
),
(
  'fusion-maia-da-nang',
  'Fusion Maia Đà Nẵng',
  'Ngũ Hành Sơn, Đà Nẵng',
  'Đà Nẵng', 'Ngũ Hành Sơn', '', '',
  'Chung cư all-inclusive spa, mỗi khách được massage miễn phí mỗi ngày.',
  'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=1200&q=80'],
  220, 'month', 5, 9.2, '890', '14.2K', 'SPA',
  ARRAY['Cable TV', 'Shop', 'Balcony', 'Bus'],
  '{"bedrooms": "3", "bathrooms": "2", "area": "97"}'::jsonb,
  '[{"icon": "fa-solid fa-spa", "text": "Spa unlimited"}, {"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi vô cực"}]'::jsonb,
  2
),
(
  'lotte-hotel-hanoi',
  'Lotte Hotel Hanoi',
  'Ba Đình, Hà Nội',
  'Hà Nội', 'Ba Đình', '', '',
  'Căn hộ 5 sao view hồ Hoàn Kiếm, buffet sáng đa dạng và phòng sang trọng.',
  'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80'],
  140, 'month', 5, 9.1, '1.650', '22.3K', 'VIEW HỒ',
  ARRAY['Washing machine', 'Cable TV', 'Heater', 'Lift'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "77"}'::jsonb,
  '[{"icon": "fa-solid fa-utensils", "text": "Buffet sáng"}, {"icon": "fa-solid fa-dumbbell", "text": "Phòng Gym"}]'::jsonb,
  2
),
(
  'pullman-phu-quoc',
  'Pullman Phú Quốc',
  'Dương Tơ, Phú Quốc',
  'Kiên Giang', 'Phú Quốc', 'Dương Tơ', '',
  'Chung cư bãi biển tại Bãi Dài, hồ bơi lớn và nhiều hoạt động cho gia đình.',
  'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=1200&q=80'],
  88, 'month', 5, 8.9, '2.100', '11.5K', 'FAMILY',
  ARRAY['Air conditioner', 'Bus', 'Heater', 'Restaurant'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "75"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi tràn bờ"}, {"icon": "fa-solid fa-child", "text": "Kids club"}]'::jsonb,
  4
),
(
  'la-siesta-hoi-an',
  'La Siesta Hội An',
  'Minh An, Hội An',
  'Quảng Nam', 'Hội An', 'Minh An', '',
  'Boutique hotel gần phố cổ, thiết kế truyền thống Việt kết hợp tiện nghi hiện đại.',
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80'],
  72, 'month', 4, 9.0, '720', '8.2K', 'BOUTIQUE',
  ARRAY['Smoking', 'Lift', 'Balcony', 'Wi Fi'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "78"}'::jsonb,
  '[{"icon": "fa-solid fa-bicycle", "text": "Xe đạp miễn phí"}, {"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi nhỏ"}]'::jsonb,
  2
),
(
  'novotel-nha-trang',
  'Novotel Nha Trang',
  'Nha Trang, Khánh Hòa',
  'Khánh Hòa', 'Nha Trang', '', '',
  'Căn hộ 4 sao view biển, giá hợp lý cho gia đình và công tác.',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80'],
  48, 'month', 4, 8.7, '1.920', '10.1K', 'GIÁ TỐT',
  ARRAY['Washing machine', 'Heater', 'Air conditioner', 'Restaurant'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "79"}'::jsonb,
  '[{"icon": "fa-solid fa-utensils", "text": "Buffet sáng"}, {"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi"}]'::jsonb,
  2
),
(
  'sheraton-nha-trang',
  'Sheraton Nha Trang',
  'Nha Trang, Khánh Hòa',
  'Khánh Hòa', 'Nha Trang', '', '',
  'Căn hộ 5 sao nằm trên bãi biển trung tâm Nha Trang.',
  'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&q=80'],
  180, 'month', 5, 9.0, '1.100', '16.4K', 'BÃI BIỂN',
  ARRAY['Balcony', 'Wi Fi', 'Bus', 'Air conditioner'],
  '{"bedrooms": "3", "bathrooms": "3", "area": "103"}'::jsonb,
  '[{"icon": "fa-solid fa-umbrella-beach", "text": "Bãi biển riêng"}, {"icon": "fa-solid fa-spa", "text": "Spa"}]'::jsonb,
  2
),
(
  'the-anam-cam-ranh',
  'The Anam Cam Ranh',
  'Cam Ranh, Khánh Hòa',
  'Khánh Hòa', 'Cam Ranh', '', '',
  'Chung cư phong cách Indochine, bãi biển dài và dịch vụ 5 sao chuẩn quốc tế.',
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&q=80'],
  152, 'month', 5, 9.3, '980', '13.2K', 'INDOCHINE',
  ARRAY['Lift', 'Balcony', 'Air conditioner', 'Smoking'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "43"}'::jsonb,
  '[{"icon": "fa-solid fa-golf-ball-tee", "text": "Sân golf"}, {"icon": "fa-solid fa-umbrella-beach", "text": "Bãi biển dài"}]'::jsonb,
  3
),
(
  'silverland-ben-thanh',
  'Silverland Ben Thanh',
  'Quận 1, TP.HCM',
  'TP.HCM', 'Quận 1', '', '',
  'Căn hộ 4 sao gần chợ Bến Thành, phù hợp du lịch và công tác.',
  'https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=1200&q=80'],
  38, 'month', 4, 8.6, '2.340', '7.8K', 'TRUNG TÂM',
  ARRAY['Wi Fi', 'Washing machine', 'Lift', 'Bus'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "40"}'::jsonb,
  '[{"icon": "fa-solid fa-utensils", "text": "Bữa sáng"}, {"icon": "fa-solid fa-location-dot", "text": "Gần chợ Bến Thành"}]'::jsonb,
  2
),
(
  'sapa-mountain-view',
  'Sapa Mountain View Hotel',
  'Sapa, Lào Cai',
  'Lào Cai', 'Sapa', '', '',
  'Căn hộ view núi Fansipan, ấm áp mùa đông và gần các bản làng.',
  'https://images.unsplash.com/photo-1528127260-dc66d52bef19?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1528127260-dc66d52bef19?w=1200&q=80'],
  44, 'month', 4, 8.8, '650', '5.1K', 'VIEW NÚI',
  ARRAY['Washing machine', 'Heater', 'Shop', 'Wi Fi'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "66"}'::jsonb,
  '[{"icon": "fa-solid fa-mountain", "text": "View núi"}, {"icon": "fa-solid fa-fire", "text": "Lò sưởi"}]'::jsonb,
  2
),
(
  'vung-tau-paradise',
  'Vũng Tàu Paradise Chung cư',
  'Bãi Sau, Vũng Tàu',
  'Bà Rịa - Vũng Tàu', 'Vũng Tàu', '', '',
  'Chung cư 4 sao sát bãi Sau, hồ bơi và nhà hàng hải sản.',
  'https://images.unsplash.com/photo-1542314831-c6a4d27ce66f?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1542314831-c6a4d27ce66f?w=1200&q=80'],
  56, 'month', 4, 8.5, '1.120', '6.3K', 'BÃI SAU',
  ARRAY['Shop', 'Lift', 'Air conditioner', 'Balcony'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "70"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi"}, {"icon": "fa-solid fa-utensils", "text": "Nhà hàng"}]'::jsonb,
  4
),
(
  'dalat-edensee',
  'Đà Lạt Edensee Lake Chung cư',
  'Xuân Thọ, Đà Lạt',
  'Lâm Đồng', 'Đà Lạt', 'Xuân Thọ', '',
  'Chung cư bên hồ Tuyền Lâm, không khí mát mẻ và view hồ tuyệt đẹp.',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80'],
  66, 'month', 4, 8.9, '580', '4.9K', 'VIEW HỒ',
  ARRAY['Wi Fi', 'Balcony', 'Lift', 'Smoking'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "41"}'::jsonb,
  '[{"icon": "fa-solid fa-water", "text": "Kayak miễn phí"}, {"icon": "fa-solid fa-mug-hot", "text": "Cà phê sáng"}]'::jsonb,
  2
),
(
  'phu-quoc-sunset-sanato',
  'Sunset Sanato Beach Chung cư',
  'Dương Tơ, Phú Quốc',
  'Kiên Giang', 'Phú Quốc', 'Dương Tơ', '',
  'Chung cư với kiến trúc độc đáo và bãi biển riêng, phù hợp cặp đôi.',
  'https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=1200&q=80'],
  108, 'month', 5, 9.1, '440', '8.2K', 'ROMANTIC',
  ARRAY['Balcony', 'Air conditioner', 'Smoking', 'Restaurant'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "46"}'::jsonb,
  '[{"icon": "fa-solid fa-umbrella-beach", "text": "Bãi biển riêng"}, {"icon": "fa-solid fa-spa", "text": "Spa"}]'::jsonb,
  2
),
(
  'hoi-an-river-view',
  'Hội An River View Homestay',
  'Cẩm Châu, Hội An',
  'Quảng Nam', 'Hội An', 'Cẩm Châu', '',
  'Homestay view sông Thu Bồn, gần phố cổ và làng rau Trà Quế.',
  'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=1200&q=80'],
  26, 'month', 3, 8.7, '320', '3.1K', '',
  ARRAY['Shop', 'Air conditioner', 'Balcony', 'Cable TV'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "33"}'::jsonb,
  '[{"icon": "fa-solid fa-bicycle", "text": "Xe đạp"}, {"icon": "fa-solid fa-kitchen-set", "text": "Bếp chung"}]'::jsonb,
  2
),
(
  'hanoi-la-siesta-trendy',
  'La Siesta Central Hotel Hanoi',
  'Hoàn Kiếm, Hà Nội',
  'Hà Nội', 'Hoàn Kiếm', '', '',
  'Boutique hotel phố cổ Hà Nội, thiết kế tinh tế và dịch vụ chu đáo.',
  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&q=80'],
  74, 'month', 4, 9.0, '1.020', '9.4K', 'PHỐ CỔ',
  ARRAY['Wi Fi', 'Air conditioner', 'Heater', 'Restaurant'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "67"}'::jsonb,
  '[{"icon": "fa-solid fa-martini-glass-citrus", "text": "Rooftop bar"}, {"icon": "fa-solid fa-bowl-food", "text": "Phở sáng"}]'::jsonb,
  2
),
(
  'da-nang-golden-bay',
  'Da Nang Golden Bay Hotel',
  'Ngũ Hành Sơn, Đà Nẵng',
  'Đà Nẵng', 'Ngũ Hành Sơn', '', '',
  'Căn hộ 5 sao với hồ bơi vô cực tầng thượng view biển Mỹ Khê.',
  'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80'],
  84, 'month', 5, 8.8, '1.890', '12.6K', 'VIEW BIỂN',
  ARRAY['Cable TV', 'Washing machine', 'Smoking', 'Balcony'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "43"}'::jsonb,
  '[{"icon": "fa-solid fa-water-ladder", "text": "Hồ bơi tầng thượng"}, {"icon": "fa-solid fa-spa", "text": "Spa"}]'::jsonb,
  2
),
(
  'nha-trang-golden-dragon',
  'Golden Dragon Hotel Nha Trang',
  'Nha Trang, Khánh Hòa',
  'Khánh Hòa', 'Nha Trang', '', '',
  'Căn hộ 3 sao giá rẻ gần biển, phù hợp du lịch bụi và nhóm đông.',
  'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80'],
  23, 'month', 3, 8.2, '890', '4.2K', 'GIÁ RẺ',
  ARRAY['Air conditioner', 'Balcony', 'Restaurant', 'Heater'],
  '{"bedrooms": "3", "bathrooms": "3", "area": "108"}'::jsonb,
  '[{"icon": "fa-solid fa-wifi", "text": "Wifi miễn phí"}, {"icon": "fa-solid fa-location-dot", "text": "Cách biển 5 phút"}]'::jsonb,
  3
),
(
  'phu-quoc-mango-bay',
  'Mango Bay Chung cư Phú Quốc',
  'Cửa Cạn, Phú Quốc',
  'Kiên Giang', 'Phú Quốc', 'Cửa Cạn', '',
  'Eco chung cư bãi ôm, ẩm thực organic và không gian yên tĩnh.',
  'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&q=80'],
  128, 'month', 4, 9.2, '290', '5.6K', 'ECO',
  ARRAY['Restaurant', 'Smoking', 'Wi Fi', 'Heater'],
  '{"bedrooms": "2", "bathrooms": "2", "area": "65"}'::jsonb,
  '[{"icon": "fa-solid fa-leaf", "text": "Ẩm thực organic"}, {"icon": "fa-solid fa-umbrella-beach", "text": "Bãi Ôm"}]'::jsonb,
  2
),
(
  'can-tho-victoria',
  'Victoria Can Tho Chung cư',
  'Ninh Kiều, Cần Thơ',
  'Cần Thơ', 'Ninh Kiều', '', '',
  'Chung cư bên sông Hậu, tour chợ nổi và ẩm thực miền Tây.',
  'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80'],
  78, 'month', 4, 8.7, '410', '4.5K', 'SÔNG NƯỚC',
  ARRAY['Smoking', 'Shop', 'Cable TV', 'Washing machine'],
  '{"bedrooms": "3", "bathrooms": "3", "area": "97"}'::jsonb,
  '[{"icon": "fa-solid fa-ship", "text": "Tour chợ nổi"}, {"icon": "fa-solid fa-utensils", "text": "Ẩm thực miền Tây"}]'::jsonb,
  2
),
(
  'ha-long-bh-cruise',
  'Bhaya Classic Cruise Hạ Long',
  'Hạ Long, Quảng Ninh',
  'Quảng Ninh', 'Hạ Long', '', '',
  'Du thuyền 2 ngày 1 đêm vịnh Hạ Long, phòng view biển và sundeck.',
  'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&q=80'],
  168, 'month', 4, 9.0, '680', '7.2K', 'CRUISE',
  ARRAY['Bus', 'Wi Fi', 'Lift', 'Restaurant'],
  '{"bedrooms": "2", "bathrooms": "1", "area": "73"}'::jsonb,
  '[{"icon": "fa-solid fa-ship", "text": "Du thuyền"}, {"icon": "fa-solid fa-utensils", "text": "Bữa ăn onboard"}]'::jsonb,
  2
),
(
  'quy-nhon-avani',
  'Avani Quy Nhơn Chung cư',
  'Nhơn Lý, Quy Nhơn',
  'Bình Định', 'Quy Nhơn', 'Nhơn Lý', '',
  'Chung cư 5 sao bãi biển Nhơn Lý, thiết kế hiện đại và ẩm thực địa phương.',
  'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80',
  ARRAY['https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80'],
  96, 'month', 5, 8.9, '320', '3.8K', 'BÌNH YÊN',
  ARRAY['Air conditioner', 'Balcony', 'Bus', 'Cable TV'],
  '{"bedrooms": "1", "bathrooms": "1", "area": "47"}'::jsonb,
  '[{"icon": "fa-solid fa-umbrella-beach", "text": "Bãi biển"}, {"icon": "fa-solid fa-spa", "text": "Spa"}]'::jsonb,
  2
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  province = EXCLUDED.province,
  district = EXCLUDED.district,
  ward = EXCLUDED.ward,
  address = EXCLUDED.address,
  description = EXCLUDED.description,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  raw_price = EXCLUDED.raw_price,
  price_type = EXCLUDED.price_type,
  stars = EXCLUDED.stars,
  rating = EXCLUDED.rating,
  reviews = EXCLUDED.reviews,
  views = EXCLUDED.views,
  badge = EXCLUDED.badge,
  amenities = EXCLUDED.amenities,
  specs = EXCLUDED.specs,
  detailed_amenities = EXCLUDED.detailed_amenities,
  max_guests = EXCLUDED.max_guests,
  updated_at = NOW();
